export interface Article {
  Alkoholhalt: number
  Argang: number
  Artikelid: number
  Ekologisk: number
  Etiskt: number
  Forpackning: string
  Forslutning: number
  Koscher: number
  Leverantor: string
  Namn: string
  Namn2: number
  PrisPerLiter: number
  Prisinklmoms: number
  Producent: string
  Provadargang: number
  Saljstart: string
  Sortiment: string
  SortimentText: string
  Stil: string
  Typ: string
  Ursprung: string
  Ursprunglandnamn: string
  Utgått: number
  Varnummer: number
  Varugrupp: string
  Volymiml: number
  nr: number
}